export interface Point {
  x: number;
  y: number;
}

export interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}

/**
 * Finds an orthogonal path from source to target that avoids obstacles.
 * Uses a non-uniform grid generated by the bounding boxes of the obstacles.
 */
export function findAutoRoute(
  source: Point,
  target: Point,
  obstacles: Rect[],
  padding: number = 24
): Point[] | null {
  // 1. Collect all interesting X and Y coordinates
  const xSet = new Set<number>();
  const ySet = new Set<number>();

  xSet.add(source.x);
  xSet.add(target.x);
  ySet.add(source.y);
  ySet.add(target.y);

  const paddedObstacles = obstacles.map(o => ({
    x: o.x - padding,
    y: o.y - padding,
    w: o.w + padding * 2,
    h: o.h + padding * 2
  }));

  paddedObstacles.forEach(o => {
    xSet.add(o.x);
    xSet.add(o.x + o.w);
    ySet.add(o.y);
    ySet.add(o.y + o.h);
  });

  const xCoords = Array.from(xSet).sort((a, b) => a - b);
  const yCoords = Array.from(ySet).sort((a, b) => a - b);

  const isInsideObstacle = (x: number, y: number) => {
    // We treat edges of the padded obstacle as passable, but strictly inside as impassable.
    // However, floating point issues might arise.
    for (const o of paddedObstacles) {
      if (x > o.x + 0.1 && x < o.x + o.w - 0.1 && y > o.y + 0.1 && y < o.y + o.h - 0.1) {
        return true;
      }
    }
    return false;
  };

  const isLineClear = (x1: number, y1: number, x2: number, y2: number) => {
    if (x1 === x2) {
      const minY = Math.min(y1, y2);
      const maxY = Math.max(y1, y2);
      for (const o of paddedObstacles) {
        // Line is vertical. If it passes strictly between left and right of an obstacle
        if (x1 > o.x + 0.1 && x1 < o.x + o.w - 0.1) {
          // Check if Y segment overlaps obstacle Y
          if (maxY > o.y + 0.1 && minY < o.y + o.h - 0.1) {
            return false;
          }
        }
      }
    } else {
      const minX = Math.min(x1, x2);
      const maxX = Math.max(x1, x2);
      for (const o of paddedObstacles) {
        // Line is horizontal.
        if (y1 > o.y + 0.1 && y1 < o.y + o.h - 0.1) {
          if (maxX > o.x + 0.1 && minX < o.x + o.w - 0.1) {
            return false;
          }
        }
      }
    }
    return true;
  };

  // 2. A* Search on the grid
  interface GraphNode {
    xi: number;
    yi: number;
    f: number;
    g: number;
    parent: GraphNode | null;
  }

  const startXi = xCoords.indexOf(source.x);
  const startYi = yCoords.indexOf(source.y);
  const targetXi = xCoords.indexOf(target.x);
  const targetYi = yCoords.indexOf(target.y);

  const openList: GraphNode[] = [];
  const closedSet = new Set<string>();

  openList.push({
    xi: startXi,
    yi: startYi,
    g: 0,
    f: Math.abs(startXi - targetXi) + Math.abs(startYi - targetYi),
    parent: null
  });

  const getHash = (xi: number, yi: number) => `${xi},${yi}`;

  let finalNode: GraphNode | null = null;

  while (openList.length > 0) {
    // Sort to get node with lowest f
    openList.sort((a, b) => a.f - b.f);
    const current = openList.shift()!;

    if (current.xi === targetXi && current.yi === targetYi) {
      finalNode = current;
      break;
    }

    const hash = getHash(current.xi, current.yi);
    if (closedSet.has(hash)) continue;
    closedSet.add(hash);

    const x = xCoords[current.xi];
    const y = yCoords[current.yi];

    // Neighbors: up, down, left, right
    const neighbors = [
      { dxi: 0, dyi: -1 },
      { dxi: 0, dyi: 1 },
      { dxi: -1, dyi: 0 },
      { dxi: 1, dyi: 0 }
    ];

    for (const n of neighbors) {
      const nx = current.xi + n.dxi;
      const ny = current.yi + n.dyi;

      if (nx >= 0 && nx < xCoords.length && ny >= 0 && ny < yCoords.length) {
        const neighborX = xCoords[nx];
        const neighborY = yCoords[ny];

        if (isInsideObstacle(neighborX, neighborY)) continue;
        if (!isLineClear(x, y, neighborX, neighborY)) continue;

        const distance = Math.abs(neighborX - x) + Math.abs(neighborY - y);
        // Add penalty for changing direction (to prefer straight lines and fewer bends)
        let bendPenalty = 0;
        if (current.parent) {
           const prevDx = Math.sign(xCoords[current.xi] - xCoords[current.parent.xi]);
           const prevDy = Math.sign(yCoords[current.yi] - yCoords[current.parent.yi]);
           const currDx = Math.sign(neighborX - x);
           const currDy = Math.sign(neighborY - y);
           if (prevDx !== currDx || prevDy !== currDy) {
              bendPenalty = 50; // Cost of adding a waypoint
           }
        }

        const g = current.g + distance + bendPenalty;
        const h = Math.abs(neighborX - target.x) + Math.abs(neighborY - target.y);
        const f = g + h;

        const nHash = getHash(nx, ny);
        if (!closedSet.has(nHash)) {
          openList.push({ xi: nx, yi: ny, g, f, parent: current });
        }
      }
    }
  }

  if (!finalNode) {
    return null;
  }

  // 3. Reconstruct path
  const path: Point[] = [];
  let curr: GraphNode | null = finalNode;
  while (curr) {
    path.unshift({ x: xCoords[curr.xi], y: yCoords[curr.yi] });
    curr = curr.parent;
  }

  // 4. Simplify path (remove collinear points)
  const simplified: Point[] = [];
  for (let i = 0; i < path.length; i++) {
    if (i === 0 || i === path.length - 1) {
      simplified.push(path[i]);
    } else {
      const prev = simplified[simplified.length - 1];
      const next = path[i + 1];
      const curr = path[i];

      const dx1 = curr.x - prev.x;
      const dy1 = curr.y - prev.y;
      const dx2 = next.x - curr.x;
      const dy2 = next.y - curr.y;

      const crossProduct = dx1 * dy2 - dy1 * dx2;
      if (Math.abs(crossProduct) > 0.1) {
        simplified.push(curr); // Not collinear, meaning it's a corner
      }
    }
  }

  if (simplified.length <= 2) return [];
  return simplified.slice(1, -1);
}
